### ISSUE TITLE
Java error on Raspberry Pi

### ISSUE THREAD

**Issue by royldean** [ac2cz/FoxTelem#460] opened 2018-03-03 12:41 UTC
Running FoxTelem 1.06j in a Raspberry Pi, unattended (or at least that is the plan).   Seems to run fine for 2 or three passes, but after that, the following error pops up every time the autostart occurs:

"java.lang.IllegalArgumentException: No line matching interface SourceDataLine supporting format PCM_SIGNED 48000.0 Hz, 16 bit, 4 bytes/frame, little-endian is supported."

If you hit "ok" in the error window, it seems that the decoder launches as normal.   However typically I'll VNC into the pi about 12 hours after starting FoxTelem and see 5 or 6 of these error boxes, and no decodes over that time.   As soon as I close the top error code window, you can restart the decoder manually (or it will restart by itself if a tracked satellite is above the horizon). 

I am using a FunCube Dongle Pro +, and the sample rate is set to the default 192000.   If I try setting it to anything lower, I still get the same error - and when you close the error the sample rate reverts to 192000.
![screenshot from 2018-03-02 17-13-54](https://user-images.githubusercontent.com/36039589/36934363-572804c2-1eb6-11e8-99c1-40c7dfa82774.png)

**Comment by ac2cz** [comment] 2018-03-03 12:55
This is a duplicate of #449. FoxTelem tries to open the audio output even if monitor audio is not set. When in an environment where the output soundcard is not available you get this error message. The fix keeps the audio output off if you toggle it off.

**Comment by ac2cz** [comment] 2018-03-03 12:58
You can download a development build from amsat.us/FoxTelem/test or wait for the patch to 1.06 which will be out soon.

**Comment by royldean** [comment] 2018-03-03 13:18
Ah, forgiveness.   I searched but didn't see it.   I'm going to plug in a cheapo usb soundcard and see if that takes care of the problem.   I'll post an update later.

**Comment by ac2cz** [comment] 2018-03-03 15:52
That would be a great test thanks. For some reason it is fine on my PI3 and not on others. It could be I have an older Raspbian build.

**Comment by royldean** [comment] 2018-03-04 15:23
Update:   24 hours running with a cheap USB soundcard plugged into the Pi, and NO ERRORS.   Note that there is nothing plugged into the souncard (ie, no headphones, no line out, etc), just the dongle plugged in and that's it.    The USB soundcard dongle is just one of those cheap $10 ones from amazon.   Raspbian Jessie (8), if that matters.   I'll update in a few days.

**Comment by ac2cz** [comment] 2018-03-10 15:25
Thanks for the report @royldean. I'm glad the workaround is working.  I'm going to close this as a duplicate of #449.

**Closed by ac2cz** 2018-03-10 15:25 UTC
Labels: duplicate
