### ISSUE TITLE
Read position from SatPC32 brings error message

### ISSUE THREAD

**Issue by dm-o** [ac2cz/FoxTelem#436] opened 2018-01-19 08:25 UTC
If I set "Read position from SatPC32" and hit "save" I get a errormessage:

![2018-01-19 09_15_17-satpc32-error](https://user-images.githubusercontent.com/25612019/35141223-9afc9a9c-fcfa-11e7-8fc5-a9cd70f640ac.png)

73
DO6DAD

**Comment by ac2cz** [comment] 2018-01-19 21:02
Thanks for the error report.  SatPC32 DDE is working for others, so I am guessing this is an issue with parsing numbers where the decimal point is a comma.  How do you configure SatPC32/Windows to use the comma instead of the period?  I would need to configure that to reproduce and test this.

**Comment by dm-o** [comment] 2018-01-20 07:50
Hi Chris,

hmm I just use the typical German windows installation with German language.
It‘s Windows 7 64Bit

Should I take some screenshots?
If so - what exactly should I send?

**Comment by ac2cz** [comment] 2018-01-20 22:31
I think I worked it out.  There are others who have faced this and there seems to be a pretty easy fix.  I can just substitute comma for period as the decimal point.  That will only get into difficulty if some localities use comma as a thousands separator and I get numbers larger than 999.  That won't be the case for AZ and EL.  I will have to test how Doppler frequency is transferred to see if that may be an issue.

**Comment by ac2cz** [comment] 2018-01-21 01:15
Should work in 1.06i, but it is hard for me to test locally.  I will make a version available to Steffan for testing.

**Comment by dm-o** [comment] 2018-01-21 09:24
Thank you very much - sounds great!
I would like to test it.

**Comment by ac2cz** [comment] 2018-01-24 01:23
Test release is available at:
http://amsat.us/FoxTelem/test/foxtelem_1.06i_windows.zip

Let me know if this works.

**Comment by dm-o** [comment] 2018-01-24 10:48
Hi Chris, 

the .exe file worked without java-warning. 

Setting SatPC32 also brought NO error message. 
How will I find out if FoxTelem will get the settings from SatPC32
correctly? 

I clicked the "Auto start" on the right site and got 2 java error
messages as you can see attached. 

73 

Steffan 

Am 2018-01-24 02:23, schrieb Chris Thompson:

> Test release is available at:
> http://amsat.us/FoxTelem/test/foxtelem_1.06i_windows.zip 
> 
> Let me know if this works. 
> 
> --
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/ac2cz/FoxTelem/issues/436#issuecomment-359989168
[2]

**Comment by ac2cz** [comment] 2018-01-24 14:03
I saw the crash with Auto Start here too.  I logged it as a separate defect.

To test SatPC32 you can change the clock on your PC so that it is during a pass.  The decoder should start.

**Closed** 2018-01-28 01:12 UTC
Labels: High
