### ISSUE TITLE
FCD Pro- Bad Behavior on RPi

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#542] opened 2019-02-18 14:55 UTC
This is from Barry, WD4ASW.  He did not realize that the original FCDP (which I call FCDP-) did not work, so he plugged it into an FIAB.  It did not appear as a source, so he chose RTL-SDR (?) and started.  He got an error box saying the device was not found, but clicking OK just brought up the error box again, so he could not get rid of FoxTelem except by rebooting (he does not know about kill etc).

Plugging in an FCDP+ apparently got him going again.

So the issue I'm reporting here is not that FCDP- is not supported but rather that it can get into an infinite loop of errors such that you can't apparently stop it easily.  I'd suggest that a device error would automatically set "start" to off.  (BTW, I tried and did not see this behavior with an FCDP+),

He also did not see that the FCDP- was not supported.  I'll update the FIAB docs; I'm not sure if it is in the FoxTelem docs or not.

**Comment by ac2cz** [comment] 2019-03-08 00:52
I can't reproduce this.  It might need to be reproduced on the PI only.  It does not happen on Windows.  We just get one message that says "Insert the Device or choose another Source." When you clear it then it is gone.

Assigning to Burns to see if this is reproducible and if a screen shot of the error is possible, to help debug.  My PI is away at another location.

**Comment by burnsfisher** [comment] 2019-03-08 01:38
I don't have an old FCDP to try it with either.  Do you want to close it?

**Comment by ac2cz** [comment] 2019-03-09 02:05
I have an FCDP that was given to me so that I can get it working on FoxTelem.  Let's hope I don't lose this one.
I tried to reproduce this issue.  The FCDP appears fine and in fact it works.  You do seem to get some USB errors, but if you click past those you can change the frequency and set the gain etc.  So this is only broken on Windows.  It is something to do with the USB HID libraries.

I was not able to reproduce the issue with the multiple error dialogues so I am going to close this as not reproducible.

**Closed** 2019-03-09 02:06 UTC
Labels: Fox In A Box/RaspPi, fcd, low priority, wontfix
