### ISSUE TITLE
Download From Server does not delete old HERCI data for 1D

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#420] opened 2018-01-12 14:49 UTC
There was apparently some old HERCI data in my FoxTelem database.  When I downloaded from the server it did not get deleted.  There was apparently no HERCI data in the database at the time.

**Comment by ac2cz** [comment] 2018-01-12 23:55
Actually, I now see that this is a duplicate of #158

**Closed by ac2cz** 2018-01-12 23:55 UTC
Labels: 1D, duplicate, low priority
