### ISSUE TITLE
Linux Command Line Args Have No Effect

### ISSUE THREAD

**Issue by burnsfisher** [ac2cz/FoxTelem#439] opened 2018-01-23 16:11 UTC
On a Pi, but it is probably true on any Linux system, I started FoxTelem 1.06h using the start_foxtelem.sh, but I edited the shell script so that the start command was

java -Xmx512M -jar FoxTelem.jar ~/Desktop/TestTelemData

Regardless, it went to the default data directory.  If there is another way to do this, it should be documented.  If not, it is a bug of some sort.  (I don't really know how Java works well enough to guess).

**Comment by ac2cz** [comment] 2018-01-23 16:14
I wonder why?  Command line args work fine on Linux for the server, because I use lots of them.  I don't think I am doing anything different for FoxTelem, but its possible.  

Did you try without the tilde?  The full path?  Though I think the shell expands that before it is passed, does it not?

**Comment by burnsfisher** [comment] 2018-01-23 16:44
I just tried it.  That made no difference.

Were you using Java on the server?  They certainly work in the standard way
for other languages.  The think I dont know is that that argument is really
an argument to "java".  Does it need something like --args to tell it to
pass them to the program it is running?

**Comment by ac2cz** [comment] 2018-01-23 21:51
This is quite odd.  I have reproduced it on Ubuntu.  If you pass is a directory without a path it works.  If the path is /home/chris/foxdata it does not work.  If you pass ../foxdata it does work.  Even though it is pointing to the same place.

**Comment by ac2cz** [comment] 2018-01-23 21:55
Ugh.  I just worked this out.  What a stupid bug...

while (arg < args.length) {
			if (args[arg].startsWith("-") || args[arg].startsWith("/")) { // this is a switch
		
On Windows /h is the same as -h on Linux.  But we don't need that any more.  This is a holdover from the days when we might run from the command line and Jerry needed to know the parameters.   This worked on windows because paths start with back slash at the shell level.

Anyway, I think we can drop support for the Windows version of switches and just require the dash.

**Comment by burnsfisher** [comment] 2018-01-23 21:56
Bizzare.  So it does relative but not absolute.  I wonder if something is
doing the relativity manually by pasting the current directory on the front?

**Comment by burnsfisher** [comment] 2018-01-23 21:58
Oops.  Even better.  Sounds like a good plan.

But wait, what about my original problem saying   ~/x/y?  Maybe the ~ is
substituted before your code?

**Comment by ac2cz** [comment] 2018-01-23 22:07
~ is fine.  The shell expands that before it makes it to FoxTelem and I just tested it to make sure it works.  Fixed in 1.06i.

**Closed** 2018-01-28 01:12 UTC
Labels: High, linux
