### ISSUE TITLE
Starting .exe in windows brings "missing java" error, using .jar works fine

### ISSUE THREAD

**Issue by dm-o** [ac2cz/FoxTelem#434] opened 2018-01-19 08:16 UTC
Hi,

I have installed JAVA (Build 1.8.0_161-b12) and when I start the FoxTelem.exe I get error message saying, that no java has been found.
When I double-click the .jar file foxtelem starts.

I did not find any specific information about the "install" process - Am I doing something wrong?

greetings, 73 
DO6DAD

**Comment by ac2cz** [comment] 2018-01-19 20:59
Thanks for logging an issue here Steffan.  I think this one may be a duplicate of issue #50.  Do you have 64 bit Java installed.  The FoxTelem.exe launcher is a 32 bit application and it only searches for 32 bit Java.  

That said, I think there is no reason why a 32 bit application can not search for 64 bit Java and launch it.  I previously thought that would need two launchers.   

The old launcher was made with JSmooth, but that is no longer supported.  I thought about building my own, but there is some complexity to it.  I have decided to build a new launcher using launch4j, which promises to support Mac and Linux.  I will put it in the next test release.  I have tested it with 64 bit Java and it seems to work.

**Comment by ac2cz** [comment] 2018-02-10 16:25
This is now part of the public release.

**Closed by ac2cz** 2018-02-10 16:25 UTC
Labels: duplicate
